### ISSUE TITLE
some questions about the configs for different datasets

### ISSUE THREAD

**Issue by check-777** [JunwenBai/MPVAE#2]
![搜狗截图20210706112937](https://user-images.githubusercontent.com/65898252/124882468-fc287b80-e002-11eb-8b81-345eafbceaed.png)
（Pytorch Version）Thanks for your nice work.I have some questions about the specific config about different datasets.For example,when I run the model on the delicious data,some metric is Nan.I consider it maybe the inappropriate parameter I used. So，could you provide all configs for all datasets you used in the paper.Thanks a lot.

**Comment by JunwenBai** [comment]
Hi,
Thx for you interest in our MPVAE paper. I have uploaded the scripts and datasets. Pls check the updated README and the `scripts` folder.
Best
