### ISSUE TITLE
some questions about construct my own datasets

### ISSUE THREAD

**Issue by yuccccci** [JunwenBai/MPVAE#3]
Thanks for your nice work.I have some questions about Which method do you use to turn text into features one hot?If it is convenient for you, could you please provide your processing code?

**Comment by JunwenBai** [comment]
Same as [LaMP](https://github.com/QData/LaMP). Features mostly come from https://mulan.sourceforge.net/datasets-mlc.html.

**Comment by yuccccci** [comment]
Thanks
