### ISSUE TITLE
some questions about data constructed by myself  loss=nan

### ISSUE THREAD

**Issue by yuccccci** [JunwenBai/MPVAE#4]
Thanks for your nice work.I have some questions  about data constructed by myself.I construct the reuters dataset as the way as the [LaMP](https://github.com/QData/LaMP). when I run the model ,some metric and loss  is Nan.But when i used the reuters dataset offered by[wenting-zhao/mavae](wget https://www.cs.cornell.edu/~junwen/data/MPVAE_data.tar.gz)  ,the run result is normal.Could you please provide the code you used to construct the dataset？

**Comment by JunwenBai** [comment]
Pls follow [wenting-zhao/mavae]. `loss=nan` might be caused by hyperparameter tuning. The data should be the same. I adapted mine from LaMP but just in the `.npy` format as described in the README.

**Comment by yuccccci** [comment]
Thanks.
